apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: booklibrary
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/NayanaShree133/booklibrary-gitops.git
    targetRevision: main
    path: helm/booklibrary
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
